eureka:
    client:
        fetchRegistry: false
        reisterWithEureka: true
        server:
            wait-time-in-ms-when-sync-empty:900
        serviceUrl:
            defaultZone:http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    instance:
        hostname: localhost
        port: 8080

server:
    port: 8081