server:
    port: 8082

eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        fetchRegistry: false
        reisterWithEureka: true        
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
        server:
            wait-time-in-ms-when-sync-empty:3000

